// <auto-generated />
namespace Colman_MVC_WebAplication_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class secound : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secound));
        
        string IMigrationMetadata.Id
        {
            get { return "202007312156583_secound"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
